Added docstrings

diff --git a/smeueger b/smeueger
--- a/smeueger
+++ b/smeueger
@@ -1,14 +1,35 @@
 #!/bin/sh
+# @name smeueger
+# @brief A script to set up a Linux system
+# @description A script to set up a Linux system with
+# - Smeueg's dotfiles (https://github.com/Smeueg/Dotfiles)
+# - Fonts (JetBrainsMono Nerd Font & Gohu Nerd Font)
+# - Rustup
+# - Flathub
+# - GTK (A GTK theme alongside an icon pack with Gruvbox colors)
+# - Matter
+# - TMPFS (on /tmp)
+# - A swapfile (/swapfile 1Gb)
+# - LightDM (Gruvbox background)
+# - Ly
+# - Enabling tap to click on a touchpad
 items=
 
+# @description Outputs a formatted string to warn the user to stdout
+# @arg $1 string The warning message
 warn() {
     printf "[\033[1;33mWARNING\033[m] %b\n" "${1}"
 }
 
+# @description Outputs a formatted string as an error to stderr
+# @arg $1 string The error message
 err() {
-    printf "[\033[1;31mERROR\033[m] %b\n" "${1}"
+    printf "[\033[1;31mERROR\033[m] %b\n" "${1}" >&2
 }
 
+# @description Checks whether a list of executables exists
+# @arg $1 item The associated item
+# @arg $2 executables The list of executables to check as a single string
 check_deps() {
     item=${1}
     exit=false
@@ -20,11 +41,12 @@ check_deps() {
     done
     if ${exit}; then
         exit 127
-    else
-        return 0
     fi
 }
 
+# @description Checks whether a list of libraries exists
+# @arg $1 item The associated item
+# @arg $2 libraries The list of libraries to check as a single string
 check_libs() {
     item=${1}
     exit=false
@@ -37,11 +59,11 @@ check_libs() {
     done
     if ${exit}; then
         exit 127
-    else
-        return 0
     fi
 }
 
+# @description Checks whether `curl` or `wget` is installed
+# @noargs
 check_curl_wget() {
     if ! { [ "$(command -v curl)" ] || [ "$(command -v wget)" ] ; }; then
         err "${1}: 'curl' and 'wget' aren't installed, either one is required"
@@ -49,14 +71,21 @@ check_curl_wget() {
     fi
 }
 
+# @description downloads a file from a url
+# @arg $1 url The url
+# @arg $2 filename The output file
 get() {
     if [ "$(command -v curl)" ]; then
         curl -Ls "$1" -o "$2"
-    else
+    elif  [ "$(command -v wget)" ]; then
         wget -q "$1" -O "$2"
     fi
 }
 
+# @description Asks the user for a yes no response
+# @arg $1 string The question
+# @exitcode 0 If user responded with a yes
+# @exitcode 1 If user responded with a no
 prompt() {
     while true; do
         printf "%b [\033[1;32mY\033[m/\033[1;31mn\033[m] " "${1}"
@@ -69,6 +98,8 @@ prompt() {
     done
 }
 
+# @description Adds an item to the global list of items
+# @arg $1 item The item to add
 items_add() {
     items="${items} ${1}"
 }
@@ -245,7 +276,6 @@ dotfiles() {
 fonts() {
     font_dir="${HOME}/.local/share/fonts/"
 	font_url="https://github.com/ryanoasis/nerd-fonts/releases/latest/download"
-
     for font in "JetBrainsMono" "Gohu"; do
         printf "Downloading '%s Nerd Font'\n" "${font}"
         mkdir -pv "${font_dir}/${font}NerdFont"
