Added 'matter' as an item to rice grub

diff --git a/smeueger b/smeueger
--- a/smeueger
+++ b/smeueger
@@ -2,20 +2,35 @@
 
 items=
 
-err() {
-    printf "\033[1;31mERROR\033[m: %b\n" "${1}"
-}
-
 warn() {
-    printf "\033[1;33mWARNING\033[m: %b\n" "${1}"
+    printf "[\033[1;33mWARNING\033[m] %b\n" "${1}"
 }
 
-check_dep() {
-    [ "$(command -v ${1})" ]
+err() {
+    printf "[\033[1;31mERROR\033[m] %b\n" "${1}"
+}
+
+check_deps() {
+    item=${1}
+    exit=false
+    for dep in ${2}; do
+        if ! [ "$(command -v ${dep})" ]; then
+            err "${item}: '${dep}' is not installed"
+            exit=true
+        fi
+    done
+    ${exit} && exit 127
+}
+
+check_curl_wget() {
+    if ! { [ "$(command -v curl)" ] || [ "$(command -v wget)" ] ; }; then
+        err "${1}: 'curl' and 'wget' aren't installed, either one is required"
+        exit 127
+    fi
 }
 
 get() {
-    if check_dep curl; then
+    if [ "$(command -v curl)" ]; then
         curl -Ls "$1" -o "$2"
     else
         wget -q "$1" -O "$2"
@@ -46,14 +61,13 @@ Usage: smeueger [-h] [ITEMS]...
 
 Items as non root:
   dotfiles  Downloads and sets up Smeueg's personal dotfiles
-  fonts     Installs the JetBrainsMono Nerd Font in ~/.local/share/fonts/,
-            requires 'curl' or 'wget'
-  rustup    Installs rustup, which is then used to install rust, cargo, and
-            rust-analyzer
+  fonts     Installs the JetBrainsMono Nerd Font in '~/.local/share/fonts/'
+  rustup    Installs 'rustup'
   flathub   Sets up Flathub for Flatpak
   gtk       Sets up a gruvbox theme for GTK using:
               - https://github.com/jmattheis/gruvbox-dark-gtk
               - https://github.com/jmattheis/gruvbox-dark-icons-gtk
+  matter    Installs 'matter' to '/tmp/', a tool to rice 'grub'
 
 Items as root:
   tmpfs       Mounts '/tmp/' as tmpfs with a size of 512MB
@@ -87,10 +101,7 @@ if [ -w / ]; then
                 items_add tmpfs
                 ;;
             swapfile)
-                if ! check_dep swapon || ! check_dep mkswap; then
-                    err "swapfile: Command 'swapon' or 'mkswap' isn't found"
-                    exit 127
-                fi
+                check_deps swapfile "swapon mkswap"
                 if [ -f /swapfile ]; then
                     err "swapfile: '/swapfile' already exists"
                     exit 3
@@ -113,43 +124,36 @@ else
     for arg in ${@}; do
         case ${arg} in
             fonts)
-                if ! { check_dep curl || check_dep wget; }; then
-                    err "fonts: 'curl' and 'wget' aren't installed, at least one is needed to be installed"
-                    exit 127
-                fi
+                check_curl_wget fonts
                 items_add fonts
                 ;;
             rustup)
-                if ! { check_dep curl || check_dep wget; }; then
-                    err "rustup: 'curl' and 'wget' aren't installed, at least one is needed to be installed"
-                    exit 127
-                fi
+                check_curl_wget rustup
                 items_add rustup
                 ;;
             dotfiles)
-                if ! check_dep git; then
-                    err "dotfiles: 'git' isn't installed"
-                    exit 127
-                fi
+                check_deps dotfiles "git"
                 items_add dotfiles
                 ;;
             flathub)
-                if ! check_dep flatpak; then
-                    err "flathub: 'flatpak' istn't installed"
-                    exit 127
-                fi
+                check_deps flathub "flatpak"
                 items_add flathub
                 ;;
             gtk)
-                if ! check_dep tar; then
-                    err "gtk: 'tar' isn't installed"
-                    exit 127
-                fi
-                if ! { check_dep curl || check_dep wget; }; then
-                    err "gtk: 'curl' and 'wget' aren't installed, at least one is needed to be installed"
-                    exit 127
-                fi
+                check_deps gtk "tar"
+                check_curl_wget gtk
                 items_add gtk
+                ;;
+            matter)
+                check_deps matter "tar"
+                check_curl_wget matter
+
+                if ! { [ -w /tmp/ ] && [ -d /tmp/ ]; }; then
+                    err "matter: /tmp is not writable or a directory"
+                    exit 1
+                fi
+
+                items_add matter
                 ;;
             -h | --help) printf "%s\n" "${help%?}"; exit 0 ;;
             *) err "Invalid item '${arg}'"; exit 1 ;;
@@ -201,6 +205,7 @@ dotfiles() {
     fi
 }
 
+
 fonts() {
 
     font_dir="${HOME}/.local/share/fonts/JetBrainsMono Nerd Font/"
@@ -231,14 +236,17 @@ fonts() {
     done
 }
 
+
 rustup() {
     get https://sh.rustup.rs - | sh
 }
+
 
 flathub() {
     flatpak remote-add --if-not-exists flathub \
             https://dl.flathub.org/repo/flathub.flatpakrepo
 }
+
 
 gtk() {
     dir_theme="${HOME}/.local/share/themes"
@@ -252,12 +260,14 @@ gtk() {
     get "${url_icons}" - | tar -xzf - -C "${dir_icons}"
 }
 
+
 tmpfs() {
     printf "tmpfs /tmp tmpfs rw,nodev,nosuid,size=512M 0 0\n" >> /etc/fstab
     if ! [ $? = 0 ]; then
         err "Failed to add '/tmp/' as tmpfs to '/etc/fstab'"
     fi
 }
+
 
 swapfile() {
     if ! dd if=/dev/zero of=/swapfile bs=1M count=1024 status=progress; then
@@ -281,11 +291,24 @@ swapfile() {
     fi
 }
 
+
 lightdm() {
     mv /etc/lightdm/lightdm-gtk-greeter.conf /etc/lightdm/lightdm-gtk-greeter.conf.backup
     printf "[greeter]\n" > /etc/lightdm/lightdm-gtk-greeter.conf
 	printf "background = #282828\n" >> /etc/lightdm/lightdm-gtk-greeter.conf
 }
+
+
+matter() {
+    printf "Downloading 'matter' to '/tmp'\n"
+    get https://github.com/mateosss/matter/archive/refs/tags/v1.2.2.tar.gz - |
+        tar -xzf - -C /tmp/
+    printf "%s\n" \
+           "" \
+           "For gruvbox, the appropriate arguments are:" \
+           "  -bg 282828 -fg EBDBB2 -hl FE8019" ""
+}
+
 
 for item in ${items}; do
     printf "[ ─ \033[1;33m%s\033[m ─ ]\n" "${item}"
