Added playlist title and clarity to the overview using colors

diff --git a/smeuesic b/smeuesic
--- a/smeuesic
+++ b/smeuesic
@@ -1,14 +1,24 @@
 #!/bin/sh
 
+# Colors
+cl_green="\033[1;32m"
+cl_red="\033[1;31m"
+cl_yellow="\033[1;33m"
+cl_blue="\033[1;34m"
+cl_magenta="\033[1;35m"
+cl_cyan="\033[1;36m"
+cl_reset="\033[0m"
+y_or_n="[${cl_green}y${cl_reset}/${cl_red}N${cl_reset}]"
+
 # Helper Functions
 if [ "${COLUMNS+x}" ]; then
 	get_cols() { COLUMNS=${COLUMNS}; }
 else
 	get_cols() { COLUMNS=$(stty size); COLUMNS=${COLUMNS#* }; }
 fi
-notice() { printf "[\033[1;32mNOTICE\033[0m] %s\n" "${1}"; }
+notice() { printf "[${cl_green}NOTICE${cl_reset}] %s\n" "${1}"; }
 error() {
-	printf "[\033[1;31mERROR\033[0m] %s\n" "${1}" >&2
+	printf "[${cl_red}ERROR${cl_reset}] %s\n" "${1}" >&2
 	exit 1
 }
 
@@ -30,7 +40,7 @@ header() {
 		str="${str}─"
 		i=$((i+1))
 	done
-	printf '\033[1;31m%s\033[0m' "${str}"
+	printf '${cl_red}%s${cl_reset}' "${str}"
 	[ "${1}" ] &&
 		printf "\r\033[$(((COLUMNS - ${#1} - 2) / 2))C ${1} \n"
 	unset str
@@ -67,36 +77,47 @@ fi
 
 
 # Ask whether to remove songs that don't exist
-remove=false
-printf "Remove local songs that aren't in the playlist? [\033[1;32my\033[0m/\033[1;31mN\033[0m] "
+printf "Remove local songs that aren't in the playlist? ${y_or_n} "
 read reply
 case ${reply} in
 	[Yy][Ee][Ss]|[Yy]) remove=true ;;
+	*) remove=false ;;
 esac
+
+if ${remove}; then
+	cl_remove="${cl_green}"
+else
+	cl_remove="${cl_red}"
+fi
+
+
+# Get playlist title
+printf "Getting playlist title, please wait..."
+pl_title=$(youtube-dl --playlist-end 1 -o "%(playlist)s" --get-filename "${pl_url}")
+printf "\r"
 
 
 # Overview for final confirmation
-printf "\033[3A\033[JOverview:\n"
-while read line; do
-	printf "  * %s\n" "${line}"
-done <<-EOF
-Playlist URL     : ${pl_url}
-Target Directory : ${music_dir}
-Remove Songs     : ${remove}
-EOF
-printf "Are you sure? [\033[1;32my\033[0m/\033[1;31mN\033[0m] "
+overview="\
+\033[3A\033[J${cl_yellow}Overview${cl_reset}
+* ${cl_cyan}Playlist${cl_reset}:
+  - ${cl_blue}Title${cl_reset}: ${pl_title}
+  - ${cl_blue}URL${cl_reset}: ${pl_url}
+* ${cl_cyan}Target Directory${cl_reset} : ${music_dir}
+* ${cl_cyan}Remove Songs${cl_reset}     : ${cl_remove}${remove}${cl_reset}
+Are you sure? ${y_or_n} "
+printf '%b' "${overview}"
 read reply
 case ${reply} in
 	[Yy][Ee][Ss]|[Yy]) ;;
-	*) exit 0;;
-esac
+		*) exit 0;;
+	esac
 
 
-# Exit if "${music_dir}" doesn't exist and can't be created
+	# Exit if "${music_dir}" doesn't exist and can't be created
 if ! [ -d "${music_dir}" ]; then
 	mkdir -pv "${music_dir}" || exit 1
 fi
-
 
 
 
@@ -151,7 +172,7 @@ sync_remove() {
 		rm -v "${music_dir%/}/${file}"
 	done
 	${ran} || printf 'No files to remove\n'
-		header
+	header
 }
 
 
