Added an entry for `ly`

diff --git a/smeueger b/smeueger
--- a/smeueger
+++ b/smeueger
@@ -14,12 +14,33 @@ check_deps() {
     item=${1}
     exit=false
     for dep in ${2}; do
-        if ! [ "$(command -v ${dep})" ]; then
+        if ! [ "$(command -v "${dep}")" ]; then
             err "${item}: '${dep}' is not installed"
             exit=true
         fi
     done
-    ${exit} && exit 127
+    if ${exit}; then
+        exit 127
+    else
+        return 0
+    fi
+}
+
+check_libs() {
+    item=${1}
+    exit=false
+    for lib in ${2}; do
+        output=$(cc -l"${lib}" 2>&1)
+        if [ "${output##*undefined reference to \`main\'*}" ]; then
+            err "${item}: 'lib${lib}' is not installed"
+            exit=true
+        fi
+    done
+    if ${exit}; then
+        exit 127
+    else
+        return 0
+    fi
 }
 
 check_curl_wget() {
@@ -40,7 +61,7 @@ get() {
 prompt() {
     while true; do
         printf "%b [\033[1;32mY\033[m/\033[1;31mn\033[m] " "${1}"
-        read response
+        read -r response
         case ${response} in
             [Yy][Ee][Ss]|[Yy]|"") return 0;;
             [Nn][Oo]|[Nn]) return 1;;
@@ -74,6 +95,7 @@ Items as root:
   swapfile    Creates a swapfile with a size of 4GB, requires 'mkswap' and
               'swapon'
   lightdm     Configures lightdm to use the gruvbox color scheme
+  ly          Installs the ly display manager
 "
 
 
@@ -85,7 +107,7 @@ fi
 
 if [ -w / ]; then
     # Items as root
-    for arg in ${@}; do
+    for arg in "${@}"; do
         case ${arg} in
             tmpfs)
                 if ! [ -f /etc/fstab ]; then
@@ -108,6 +130,11 @@ if [ -w / ]; then
                 fi
                 items_add swapfile
                 ;;
+            ly)
+                check_deps ly "cc make git sed"
+                check_libs ly "pam xcb"
+                items_add ly
+                ;;
             lightdm)
                 if ! [ -f /etc/lightdm/lightdm-gtk-greeter.conf ]; then
                     err "'/etc/lightdm/lightdm-gtk-greeter.conf' doesn't exist"
@@ -121,7 +148,7 @@ if [ -w / ]; then
     done
 else
     # Items as non root
-    for arg in ${@}; do
+    for arg in "${@}"; do
         case ${arg} in
             fonts)
                 check_curl_wget fonts
@@ -168,7 +195,7 @@ dotfiles() {
 
     if [ -d "${dots_dir}" ]; then
         if ! prompt "'${dots_dir}' already exists, overwrite it?"; then
-            printf "Won't overwrite '${dots_dir}'\n"
+            printf "Won't overwrite '%s'\n" "${dots_dir}"
             return
         fi
     fi
@@ -187,7 +214,9 @@ dotfiles() {
         if [ -f "${HOME}/${file}" ]; then
             backup_dir="${HOME}/DotsBackup/${file}"
             backup_dir=${backup_dir%/*}
-            printf "Backing up '${HOME}/${file}' to '${backup_dir}'\n"
+            printf "Backing up '%s' to '%s'\n" \
+                   "${HOME}/${file}" \
+                   "${backup_dir=}"
             if ! mkdir -p "${backup_dir}"; then
                 err "Failed to create directory '${backup_dir}'"
                 return 1
@@ -211,7 +240,7 @@ fonts() {
 	font_url="https://github.com/ryanoasis/nerd-fonts/releases/latest/download"
 
     for font in "JetBrainsMono" "Gohu"; do
-        printf "Downloading '%s Nerd Font'\n"
+        printf "Downloading '%s Nerd Font'\n" "${font}"
         mkdir -pv "${font_dir}/${font}NerdFont"
         get "${font_url}/${font}.tar.xz" - |
             tar -xJf - -C "${font_dir}/${font}NerdFont"
@@ -244,8 +273,8 @@ gtk() {
 
 
 tmpfs() {
-    printf "tmpfs /tmp tmpfs rw,nodev,nosuid,size=512M 0 0\n" >> /etc/fstab
-    if ! [ $? = 0 ]; then
+    entry="tmpfs /tmp tmpfs rw,nodev,nosuid,size=512M 0 0"
+    if ! printf "%s\n" "${entry}" >> /etc/fstab; then
         err "Failed to add '/tmp/' as tmpfs to '/etc/fstab'"
     fi
 }
@@ -275,7 +304,8 @@ swapfile() {
 
 
 lightdm() {
-    mv /etc/lightdm/lightdm-gtk-greeter.conf /etc/lightdm/lightdm-gtk-greeter.conf.backup
+    lightdm_conf="/etc/lightdm/lightdm-gtk-greeter.conf "
+    mv "${lightdm_conf}" "${lightdm_conf}.backup"
     printf "[greeter]\n" > /etc/lightdm/lightdm-gtk-greeter.conf
 	printf "background = #282828\n" >> /etc/lightdm/lightdm-gtk-greeter.conf
 }
@@ -292,10 +322,39 @@ matter() {
 }
 
 
+ly() {
+    repo_url="https://github.com/fairyglade/ly"
+    repo_dir="/tmp/ly"
+    if ! git clone --recurse-submodules "${repo_url}" "${repo_dir}"; then
+        err "Failed to clone '${repo_url}' to '${repo_dir}'"
+        return 1
+    fi
+    if ! make --directory="${repo_dir}" install; then
+        err "Failed to run 'make install' on '${repo_dir}'"
+        return 1
+    fi
+    if [ "$(command -v systemctl)" ]; then
+        make --directory="${repo_dir}" installsystemd &&
+            systemctl enable ly.service --force
+        bg="282828"
+        fg="ebdbb2"
+        escape_sequence_sed="\\\\033]P0${bg}\\\\033]P7${fg}\\\\033c"
+        escape_sequence_printf="\\033]P0${bg}\\033]P7${fg}\\033c"
+        sed -i "/^\[Service\]/a ExecStartPre=/usr/bin/printf '%%b' '${escape_sequence_sed}'"\
+            /lib/systemd/system/ly.service
+        printf "term_reset_cmd = /usr/bin/tput reset; /usr/bin/printf '%%b' '%s'\n" \
+               "${escape_sequence_printf}" >> /etc/ly/config.ini
+    fi
+}
+
+
 for item in ${items}; do
     printf "[ ─ \033[1;33m%s\033[m ─ ]\n" "${item}"
-    ${item}
-    printf "Finished setting up %s...\n\n" "${item}"
+    if ${item}; then
+        printf "Finished setting up %s...\n\n" "${item}"
+    else
+        printf "Failed setting up %s...\n\n" "${item}"
+    fi
 done
 
 printf "\033[A"
